name: Backend Docker Release

on:
  push:
    branches:
      - main
      - 'pr/**'      
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      FRONTEND_REPO: org/app
      FRONTEND_BRANCH: main

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout frontend repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.FRONTEND_REPO }}
          ref: ${{ env.FRONTEND_BRANCH }}
          path: frontend

      - name: Extract version
        id: version
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f frontend/pom.xml)
          BASE_VERSION="${BASE_VERSION#v}"

          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
            VERSION="${BASE_VERSION}-pr-${PR_NUMBER}"
          else
            VERSION="$BASE_VERSION"
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Final Docker version: $VERSION"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VERSION=$VERSION \
            -t ghcr.io/${{ github.repository }}:$VERSION \
            -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:$VERSION
          docker push ghcr.io/${{ github.repository }}:latest
